spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservicio_product_v2?serverTimezone=UTC
    username: root
    password: Kojinanjo1@
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
active-mq:
  broker-url: tcp://localhost:61616
  product-low-stock-queue: product.low-stock.queue

server:
  port: 8080
